services:
  api:
    build: ./api
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html/backend
      - ./.htaccess:/var/www/html/.htaccess
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: aetheria
      DB_USER: postgres
      DB_PASS: Passw0rd

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aetheria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Passw0rd
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

volumes:
  pgdata:
